### PR TITLE
Add addon comment on CodeEditor

### LINKED ISSUE #82: TypeError: e.toggleComment is not a function
Sentry Issue: [CODEPAIR-7](https://sentry.io/organizations/yorkie-team/issues/2283939197/?referrer=github_integration)

```
TypeError: e.toggleComment is not a function
  at HTMLTextAreaElement.n (../../src/helpers.ts:87:17)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ppeeou**
#### What this PR does / why we need it?

Add addon comment
Users can use the editor comment toggle function.

#### What are the relevant tickets?

Fixes #82

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Review by hackerwins — APPROVED** [review]
Thanks for the contribution. What kind of behavior is it related to?

**Comment by ppeeou** [comment]
@hackerwins  

If we do not provide an addon when using a keymap that generates annotations in the Codemirror editor, an error occurs.


If you want to generate an error, you can check it using the keymap below on 
mac [command + /]

**Comment by ppeeou** [comment]
> Thanks for the contribution. What kind of behavior is it related to?

Oh sorry, I gave a different answer to your question.

As in issue #82, if you input `[command + /]` without addon, a script error occurs as shown below.

image

Accordingly, if we add addon in this PR and input `[command + /]`, we can see comments and no script error occurs.

image

**Comment by hackerwins** [comment]
@ppeeou Thank you for the detailed explanation.

**Pull request merged**
