### PR TITLE
Change mobile environment UI

### PR DESCRIPTION
**Pull request by ppeeou**
#### What this PR does / why we need it?

When three or more users are added in mobile environment, the screen overflows.
Make the share button appear from the screen size "sm" or larger.

image

#### What are the relevant tickets?

Fixes #

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Comment by mojosoeun** [comment]
@ppeeou Thank you for your PR! 
I think it would be great to show the `share` button just using CSS rather than using JavaScript :)

**Comment by ppeeou** [comment]
Thank you for your comment. 
 I'm going to try it css instead of using javascript

**Comment by mojosoeun** [comment]
@ppeeou I think it would be great to use `scss`. If we register sass-loader in webpack.config.js, we can import the scss file

**Comment by ppeeou** [comment]
@mojosoeun I applied it :)

**Pull request merged**
