### PR TITLE
Provides a drawing square

### LINKED ISSUE #65: Improving the drawing board
**Description**:

We added basic features, line drawing and an eraser to the drawing board.
We need to add features such as line style or shapes so that users can draw more various content.

I think it will be helpful to refer to the UI of [Jamboard](https://jamboard.google.com/) or [Zoom's annotation tool](https://support.zoom.us/hc/en-us/articles/115005706806-Using-annotation-tools-on-a-shared-screen-or-whiteboard).

Screen Shot 2021-03-15 at 9 45 19

**Why**:

Users can draw various contents on the drawing board.

### PR DESCRIPTION
**Pull request by ppeeou**
#### What this PR does / why we need it?

Provides a function to draw a square

It helps users to express a schematic reporesentation.
image

Features to add

- Draw a square
- Select and move

Features to be added in the future

- Text provided
- Square size adjustment function

#### What are the relevant tickets?

Fixes #65 

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Review by hackerwins — COMMENTED** [review]
In this PR there are asynchronous function connections. Can you explain why we need it?

**Comment by ppeeou** [comment]
> In this PR there are asynchronous function connections. Can you explain why we need it?

Thank you for your comment 👍

There is no need to change to an asynchronous function because asynchronous function does not occur in the update of yorkie-sdk-js

I wanted to express that data is returned directly from the callback funtion

**Comment by hackerwins** [comment]
Asynchronous functions increase the complexity compared to synchronous functions. Since there is [a bug related to drawing](https://github.com/yorkie-team/yorkie-codepair/issues/77), I suggest expressing it as synchronous functions.

**Comment by ppeeou** [comment]
@hackerwins  I'd better do that 😄  I've modified it

**Review by hackerwins — APPROVED** [review]
LGTM. 👍

**Pull request merged**
