### PR TITLE
Add package manager lock file and bump up chokidar

### LINKED ISSUE #136: Bump up the chokidar package, or change package manager.
**Description**:
image
We need to run `npm update --package-lock chokidar`or Change package manager to yarn(for [lock file consistency](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion)).

If we change package manager to yarn, We need to change the [code](https://github.com/yorkie-team/yorkie-codepair/blob/1ad33d0f1f73b541b3a1cbff5428093d915e05a7/webapp/src/components/Editor/Editor.tsx#L39) like [example](https://material-ui.com/styles/api/#examples-3).

**Why**:
Because up to node 14+, `chokidar@2` doesn't work [related issue](https://github.com/facebook/create-react-app/issues/10811).

### PR DESCRIPTION
**Pull request by SimYunSup**
#### What this PR does / why we need it?
Add yarn lock file and bump up chokidar for node 14+.
Add development guide for yarn.

#### What are the relevant tickets?
Fixes #136 #137 .

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Review by ppeeou — APPROVED** [review]
LGTM:)

**Review by hackerwins — COMMENTED** [review]
Thanks for the contribution. I left two questions.

1. Is it beneficial to us to support both package managers at the same time?
2. Are there any other project examples that support both package managers at the same time?

**Comment by SimYunSup** [comment]
@hackerwins 
1. I don't think There are not beneficial for development, but only for npm users. So, I suggested "Change package manager" because many repository choose package manager as yarn.
2. As far as I can remember, hackatalk use both package managers at the same time, but they finally choose yarn.

**Comment by hackerwins** [comment]
I think supporting both package managers only increases complexity.

In this PR, how about just an update the library?

**Comment by mojosoeun** [comment]
I agree with @hackerwins!

**Comment by SimYunSup** [comment]
Then, I can't commit code for 2 days. So, Can you delete yarn.lock file and development guide for yarn? And you must add guide that development environment must be node 16+

**Comment by hackerwins** [comment]
@SimYunSup Thank you for the answer.
It's not urgent, so please update when you have time.

**Comment by hackerwins** [comment]
@SimYunSup Is this PR still going on?

**Comment by hackerwins** [comment]
This PR looks like we shouldn't have to go ahead. I will close it and reopen it later if it becomes a problem.

**Pull request closed without merging**
